[package]
name = "gml-parser"
version = "0.2.0"
authors = ["The OpenGMK Project Developers"]
edition = "2021"
rust-version = "1.59"

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = []
runner-serde-derives = ["serde"]
