[package]
name = "gm8exe"
version = "0.2.0"
authors = ["The OpenGMK Project Developers"]
license = "GPL-2.0-only"
edition = "2021"
rust-version = "1.59"

[dependencies]
byteorder = "1"
flate2 = { version = "1.0", features = ["rust_backend"] }
rayon = "1.2.0"
